### ISSUE TITLE
app won't close (trainer) and keeps running in the background

### ISSUE THREAD

**Issue by ahjolinna** [wyyadd/LaLa#12] opened 2023-11-07 03:49 UTC
so I notice that trainers keeps running in the background even after I have closed the app, this happens on both flatpak and AppImage ...and for example if I opened the trainer on flatpak then closed the app then reopened the same trainer with Appimage it opened both version of the trainers...BUT the background process amount keep increasing (especially the .cache every time you launch a trainer, even if its the same trainer)

![image](https://github.com/wyyadd/LaLa/assets/6993072/ccad6595-6a0f-456a-bb8c-0838851e78e5)
![image](https://github.com/wyyadd/LaLa/assets/6993072/01f2b7d9-3dd1-437f-8124-c098bcec74ad)

**Comment by wyyadd** [comment] 2023-11-07 04:09
Could provide me with the trainer name that you test with?

**Comment by ahjolinna** [comment] 2023-11-07 04:53
I have been testing mainly with Hogwarts Legacy and Baldur's Gate 3 on my desktop, and Octopath Traveler on SteamDeck  (with 10% CPU usage)

when I tested Persona 4 Golden and Persona 5 Royal on SteamDeck they didnt have this issue, also noticed that Soul Hackers 2 didn't launch at all

PS. one issue with AppImage version seems to stop working because of this, what I mean that you cant relaunch it when this happens


![image](https://github.com/wyyadd/LaLa/assets/6993072/0acfd46b-5216-4599-b95f-33c1c60bbf43)

**Comment by wyyadd** [comment] 2023-11-07 05:17
> I have been testing mainly with Hogwarts Legacy and Baldur's Gate 3 on my desktop, and Octopath Traveler on SteamDeck (with 10% CPU usage)
when I tested Persona 4 Golden and Persona 5 Royal on SteamDeck they didnt have this issue, 

It should be a trainer related issue. Although I can't reproduce it, I will fix it by killing all processes before closing LaLa, as that would be safer. 

> also noticed that Soul Hackers 2 didn't launch at all

It is also a trainer related issue. see:https://github.com/wyyadd/LaLa/issues/4 
BTW, The flickering issue https://github.com/wyyadd/LaLa/issues/6 is also related to some specific trainers.
Sigh, it seems that Fling Trainers don't run very well on Linux. 

> PS. one issue with AppImage version seems to stop working because of this, what I mean that you cant relaunch it when this happens
also seems that the whole app is running in the background

Could you please provide more details, including the steps to reproduce and any error messages encountered?

**Comment by ahjolinna** [comment] 2023-11-07 11:57
I notice that this seems to be a nvidia driver issue, I assume ...cant 100% confirm. but on my AMD laptop I dont have any these issues.

**Comment by wyyadd** [comment] 2023-11-09 02:52
Update: 
I fixed this issue In release [v1.0.5](https://github.com/wyyadd/LaLa/releases/tag/v1.0.5) .

**Closed by wyyadd** 2023-11-09 02:52 UTC
